name: mezmaps
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2


  equatable: ^2.0.5
  get_it: ^8.0.0

  common:
    path: module/common

  gen:
    path: module/gen

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
